/**
 * DataTransparency
 *
 * Shows the data sources powering the predictions plus an
 * accuracy / freshness disclaimer. Builds trust with the
 * public by being upfront about methodology.
 */

import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import {
  Cloud,
  Database,
  FileText,
  Radio,
  TreePine,
  Users,
} from "lucide-react";

const SOURCES = [
  {
    icon: Cloud,
    name: "OpenWeatherMap",
    desc: "Real-time temperature, humidity, precipitation",
    refresh: "Every 60 min",
  },
  {
    icon: Radio,
    name: "PAGASA",
    desc: "Philippine weather station observations",
    refresh: "Merged at training time",
  },
  {
    icon: FileText,
    name: "DRRMO Parañaque",
    desc: "3,700 + official flood records (2022–2025)",
    refresh: "Updated per release",
  },
  {
    icon: TreePine,
    name: "Random Forest Model",
    desc: "v6 classifier with 10-fold cross-validation",
    refresh: "Retrained per version",
  },
  {
    icon: Database,
    name: "Google Earth Engine",
    desc: "Fallback weather data (CHIRPS, ERA5)",
    refresh: "Circuit-breaker fallback",
  },
  {
    icon: Users,
    name: "Community Reports",
    desc: "Resident-submitted flood observations",
    refresh: "Real-time",
  },
] as const;

export function DataTransparency() {
  return (
    <Card>
      <CardHeader className="pb-3">
        <CardTitle className="text-base flex items-center gap-2">
          <Database className="h-4 w-4 text-muted-foreground" />
          Data Sources &amp; Methodology
        </CardTitle>
      </CardHeader>
      <CardContent className="space-y-4">
        {/* Source table */}
        <div className="overflow-x-auto">
          <table className="w-full text-sm" aria-label="Data sources">
            <thead>
              <tr className="text-left border-b border-border/40">
                <th className="pb-2 font-medium text-muted-foreground text-xs">
                  Source
                </th>
                <th className="pb-2 font-medium text-muted-foreground text-xs hidden sm:table-cell">
                  Description
                </th>
                <th className="pb-2 font-medium text-muted-foreground text-xs text-right">
                  Refresh
                </th>
              </tr>
            </thead>
            <tbody className="divide-y divide-border/20">
              {SOURCES.map((s) => {
                const Icon = s.icon;
                return (
                  <tr key={s.name} className="text-sm">
                    <td className="py-2 pr-3">
                      <div className="flex items-center gap-2">
                        <Icon className="h-3.5 w-3.5 text-muted-foreground shrink-0" />
                        <span className="font-medium">{s.name}</span>
                      </div>
                    </td>
                    <td className="py-2 text-muted-foreground hidden sm:table-cell">
                      {s.desc}
                    </td>
                    <td className="py-2 text-muted-foreground text-right text-xs">
                      {s.refresh}
                    </td>
                  </tr>
                );
              })}
            </tbody>
          </table>
        </div>

        {/* Disclaimer */}
        <div className="rounded-lg bg-muted/30 p-3 text-xs text-muted-foreground space-y-1.5">
          <p className="font-medium text-foreground text-xs">Disclaimer</p>
          <p>
            Predictions are generated by a Random Forest machine-learning model
            and should be treated as decision-support information, not absolute
            forecasts. Always follow official DRRMO advisories and PAGASA
            bulletins during typhoon or heavy-rain events.
          </p>
          <p>
            Weather data may be simulated when the OpenWeatherMap API key is
            unavailable in development mode.
          </p>
        </div>
      </CardContent>
    </Card>
  );
}
