"""add community reports and evacuation tables

Revision ID: 7ea25273d2b4
Revises: n9o0p1q2r3s4
Create Date: 2026-03-05 00:36:25.659095

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7ea25273d2b4'
down_revision: Union[str, Sequence[str], None] = 'o0p1q2r3s4t5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('evacuation_centers',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('barangay', sa.String(length=100), nullable=False),
    sa.Column('address', sa.Text(), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('capacity_total', sa.Integer(), nullable=False),
    sa.Column('capacity_current', sa.Integer(), nullable=False),
    sa.Column('contact_number', sa.String(length=20), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    comment='Designated evacuation centers in Parañaque City'
    )
    op.create_index('idx_evac_active', 'evacuation_centers', ['is_active', 'is_deleted'], unique=False)
    op.create_index('idx_evac_barangay', 'evacuation_centers', ['barangay'], unique=False)
    op.create_index('idx_evac_coords', 'evacuation_centers', ['latitude', 'longitude'], unique=False)
    op.create_index(op.f('ix_evacuation_centers_is_active'), 'evacuation_centers', ['is_active'], unique=False)
    op.create_index(op.f('ix_evacuation_centers_is_deleted'), 'evacuation_centers', ['is_deleted'], unique=False)
    op.create_table('incidents',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('incident_type', sa.String(length=50), nullable=False),
    sa.Column('risk_level', sa.Integer(), nullable=False),
    sa.Column('barangay', sa.String(length=100), nullable=False),
    sa.Column('location_detail', sa.String(length=255), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('confirmed_by', sa.String(length=100), nullable=True),
    sa.Column('confirmed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('broadcast_sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('broadcast_channels', sa.String(length=255), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resolved_by', sa.String(length=100), nullable=True),
    sa.Column('affected_families', sa.Integer(), nullable=True),
    sa.Column('evacuated_families', sa.Integer(), nullable=True),
    sa.Column('casualties', sa.Integer(), nullable=True),
    sa.Column('estimated_damage', sa.Float(), nullable=True),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('related_alert_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.String(length=100), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    comment='LGU flood incident tracking (RA 10121 compliant)'
    )
    op.create_index('idx_incident_active', 'incidents', ['is_deleted', 'created_at'], unique=False)
    op.create_index('idx_incident_barangay', 'incidents', ['barangay'], unique=False)
    op.create_index('idx_incident_risk', 'incidents', ['risk_level'], unique=False)
    op.create_index('idx_incident_status', 'incidents', ['status'], unique=False)
    op.create_index('idx_incident_status_risk', 'incidents', ['status', 'risk_level'], unique=False)
    op.create_index(op.f('ix_incidents_created_at'), 'incidents', ['created_at'], unique=False)
    op.create_index(op.f('ix_incidents_is_deleted'), 'incidents', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_incidents_related_alert_id'), 'incidents', ['related_alert_id'], unique=False)
    op.create_table('after_action_reports',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('incident_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('timeline', sa.Text(), nullable=True),
    sa.Column('response_actions', sa.Text(), nullable=True),
    sa.Column('resources_deployed', sa.Text(), nullable=True),
    sa.Column('response_time_minutes', sa.Integer(), nullable=True),
    sa.Column('evacuation_time_minutes', sa.Integer(), nullable=True),
    sa.Column('warning_lead_time_minutes', sa.Integer(), nullable=True),
    sa.Column('prediction_accuracy', sa.Float(), nullable=True),
    sa.Column('lessons_learned', sa.Text(), nullable=True),
    sa.Column('recommendations', sa.Text(), nullable=True),
    sa.Column('follow_up_actions', sa.Text(), nullable=True),
    sa.Column('ra10121_compliant', sa.Boolean(), nullable=False),
    sa.Column('submitted_to_ndrrmc', sa.Boolean(), nullable=False),
    sa.Column('submitted_to_dilg', sa.Boolean(), nullable=False),
    sa.Column('prepared_by', sa.String(length=100), nullable=True),
    sa.Column('reviewed_by', sa.String(length=100), nullable=True),
    sa.Column('approved_by', sa.String(length=100), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['incident_id'], ['incidents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    comment='After-action reports per RA 10121 compliance'
    )
    op.create_index('idx_aar_active', 'after_action_reports', ['is_deleted', 'created_at'], unique=False)
    op.create_index('idx_aar_incident', 'after_action_reports', ['incident_id'], unique=False)
    op.create_index('idx_aar_status', 'after_action_reports', ['status'], unique=False)
    op.create_index(op.f('ix_after_action_reports_incident_id'), 'after_action_reports', ['incident_id'], unique=False)
    op.create_index(op.f('ix_after_action_reports_is_deleted'), 'after_action_reports', ['is_deleted'], unique=False)
    op.create_table('community_reports',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('barangay', sa.String(length=100), nullable=True),
    sa.Column('flood_height_cm', sa.Integer(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('photo_url', sa.Text(), nullable=True),
    sa.Column('risk_label', sa.String(length=10), nullable=False),
    sa.Column('credibility_score', sa.Float(), nullable=False),
    sa.Column('verified', sa.Boolean(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('confirmation_count', sa.Integer(), nullable=False),
    sa.Column('dispute_count', sa.Integer(), nullable=False),
    sa.Column('abuse_flag_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    comment='Crowdsourced flood reports from community members'
    )
    op.create_index('idx_report_barangay', 'community_reports', ['barangay'], unique=False)
    op.create_index('idx_report_coords', 'community_reports', ['latitude', 'longitude'], unique=False)
    op.create_index('idx_report_created_desc', 'community_reports', [sa.text('created_at DESC')], unique=False)
    op.create_index('idx_report_status', 'community_reports', ['status'], unique=False)
    op.create_index(op.f('ix_community_reports_created_at'), 'community_reports', ['created_at'], unique=False)
    op.create_index(op.f('ix_community_reports_is_deleted'), 'community_reports', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_community_reports_user_id'), 'community_reports', ['user_id'], unique=False)
    op.create_table('evacuation_alert_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('center_id', sa.Integer(), nullable=True),
    sa.Column('sms_status', sa.String(length=20), nullable=False),
    sa.Column('channel', sa.String(length=20), nullable=False),
    sa.Column('barangay', sa.String(length=100), nullable=True),
    sa.Column('risk_label', sa.String(length=10), nullable=True),
    sa.Column('message_text', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['center_id'], ['evacuation_centers.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    comment='Immutable audit trail for evacuation alert dispatches'
    )
    op.create_index('idx_alert_log_barangay', 'evacuation_alert_logs', ['barangay'], unique=False)
    op.create_index('idx_alert_log_created', 'evacuation_alert_logs', ['created_at'], unique=False)
    op.create_index('idx_alert_log_status', 'evacuation_alert_logs', ['sms_status'], unique=False)
    op.create_index(op.f('ix_evacuation_alert_logs_center_id'), 'evacuation_alert_logs', ['center_id'], unique=False)
    op.create_index(op.f('ix_evacuation_alert_logs_created_at'), 'evacuation_alert_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_evacuation_alert_logs_user_id'), 'evacuation_alert_logs', ['user_id'], unique=False)
    # NOTE: The following ALTER COLUMN and index renames are skipped for SQLite compatibility.
    # On PostgreSQL, these would normalise index names for alert_history, satellite_weather_cache,
    # tide_data_cache, and users tables.  Apply manually if running against PostgreSQL.
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_evacuation_alert_logs_user_id'), table_name='evacuation_alert_logs')
    op.drop_index(op.f('ix_evacuation_alert_logs_created_at'), table_name='evacuation_alert_logs')
    op.drop_index(op.f('ix_evacuation_alert_logs_center_id'), table_name='evacuation_alert_logs')
    op.drop_index('idx_alert_log_status', table_name='evacuation_alert_logs')
    op.drop_index('idx_alert_log_created', table_name='evacuation_alert_logs')
    op.drop_index('idx_alert_log_barangay', table_name='evacuation_alert_logs')
    op.drop_table('evacuation_alert_logs')
    op.drop_index(op.f('ix_community_reports_user_id'), table_name='community_reports')
    op.drop_index(op.f('ix_community_reports_is_deleted'), table_name='community_reports')
    op.drop_index(op.f('ix_community_reports_created_at'), table_name='community_reports')
    op.drop_index('idx_report_status', table_name='community_reports')
    op.drop_index('idx_report_created_desc', table_name='community_reports')
    op.drop_index('idx_report_coords', table_name='community_reports')
    op.drop_index('idx_report_barangay', table_name='community_reports')
    op.drop_table('community_reports')
    op.drop_index(op.f('ix_after_action_reports_is_deleted'), table_name='after_action_reports')
    op.drop_index(op.f('ix_after_action_reports_incident_id'), table_name='after_action_reports')
    op.drop_index('idx_aar_status', table_name='after_action_reports')
    op.drop_index('idx_aar_incident', table_name='after_action_reports')
    op.drop_index('idx_aar_active', table_name='after_action_reports')
    op.drop_table('after_action_reports')
    op.drop_index(op.f('ix_incidents_related_alert_id'), table_name='incidents')
    op.drop_index(op.f('ix_incidents_is_deleted'), table_name='incidents')
    op.drop_index(op.f('ix_incidents_created_at'), table_name='incidents')
    op.drop_index('idx_incident_status_risk', table_name='incidents')
    op.drop_index('idx_incident_status', table_name='incidents')
    op.drop_index('idx_incident_risk', table_name='incidents')
    op.drop_index('idx_incident_barangay', table_name='incidents')
    op.drop_index('idx_incident_active', table_name='incidents')
    op.drop_table('incidents')
    op.drop_index(op.f('ix_evacuation_centers_is_deleted'), table_name='evacuation_centers')
    op.drop_index(op.f('ix_evacuation_centers_is_active'), table_name='evacuation_centers')
    op.drop_index('idx_evac_coords', table_name='evacuation_centers')
    op.drop_index('idx_evac_barangay', table_name='evacuation_centers')
    op.drop_index('idx_evac_active', table_name='evacuation_centers')
    op.drop_table('evacuation_centers')
    # ### end Alembic commands ###
