#!/bin/sh
# =====================================================
# FLOODINGNAQUE - PgBouncer Entrypoint Script
# =====================================================
# Configures PgBouncer with environment variables
# Supports Docker Secrets with _FILE suffix pattern
# =====================================================

set -e

# =====================================================
# Docker Secrets _FILE Pattern Support
# =====================================================
# Function to read secret from file if _FILE env var is set
# Usage: read_secret "VAR_NAME" "default_value"
# Checks VAR_NAME_FILE first, then VAR_NAME, then uses default
read_secret() {
    local var_name="$1"
    local default_value="$2"
    local file_var_name="${var_name}_FILE"
    
    # Get the value of the _FILE variable
    eval "local file_path=\${$file_var_name:-}"
    
    if [ -n "$file_path" ] && [ -f "$file_path" ]; then
        # Read from file, trim whitespace
        cat "$file_path" | tr -d '\n\r'
        return
    fi
    
    # Fall back to direct environment variable
    eval "local env_value=\${$var_name:-}"
    if [ -n "$env_value" ]; then
        echo "$env_value"
        return
    fi
    
    # Return default if nothing else works
    echo "$default_value"
}

# =====================================================
# Default Configuration Values
# =====================================================
DB_HOST="${DB_HOST:-localhost}"
DB_PORT="${DB_PORT:-5432}"
DB_NAME="${DB_NAME:-floodingnaque}"
DB_USER="${DB_USER:-postgres}"
# Support _FILE pattern for passwords
DB_PASSWORD=$(read_secret "DB_PASSWORD" "")
if [ -z "$DB_PASSWORD" ]; then
    echo "ERROR: DB_PASSWORD must be set (via DB_PASSWORD or DB_PASSWORD_FILE)" >&2
    exit 1
fi
DB_SSL_MODE="${DB_SSL_MODE:-require}"

# Read replica defaults (fallback to primary)
DB_REPLICA_HOST="${DB_REPLICA_HOST:-$DB_HOST}"
DB_REPLICA_PORT="${DB_REPLICA_PORT:-$DB_PORT}"

# PgBouncer settings (these don't need _FILE as they're not secrets)
PGBOUNCER_POOL_MODE="${PGBOUNCER_POOL_MODE:-transaction}"
PGBOUNCER_MAX_CLIENT_CONN="${PGBOUNCER_MAX_CLIENT_CONN:-1000}"
PGBOUNCER_DEFAULT_POOL_SIZE="${PGBOUNCER_DEFAULT_POOL_SIZE:-25}"
PGBOUNCER_MIN_POOL_SIZE="${PGBOUNCER_MIN_POOL_SIZE:-5}"
PGBOUNCER_RESERVE_POOL_SIZE="${PGBOUNCER_RESERVE_POOL_SIZE:-10}"
PGBOUNCER_MAX_DB_CONNECTIONS="${PGBOUNCER_MAX_DB_CONNECTIONS:-50}"

# Admin users - Support _FILE pattern for admin/stats passwords
PGBOUNCER_ADMIN_USER="${PGBOUNCER_ADMIN_USER:-pgbouncer_admin}"
PGBOUNCER_ADMIN_PASSWORD=$(read_secret "PGBOUNCER_ADMIN_PASSWORD" "admin_password_change_me")
PGBOUNCER_STATS_USER="${PGBOUNCER_STATS_USER:-pgbouncer_stats}"
PGBOUNCER_STATS_PASSWORD=$(read_secret "PGBOUNCER_STATS_PASSWORD" "stats_password_change_me")

echo "========================================"
echo "Floodingnaque PgBouncer Initialization"
echo "========================================"
echo "Primary DB: ${DB_HOST}:${DB_PORT}/${DB_NAME}"
echo "Replica DB: ${DB_REPLICA_HOST}:${DB_REPLICA_PORT}/${DB_NAME}"
echo "Pool Mode: ${PGBOUNCER_POOL_MODE}"
echo "Max Client Connections: ${PGBOUNCER_MAX_CLIENT_CONN}"
echo "Default Pool Size: ${PGBOUNCER_DEFAULT_POOL_SIZE}"
echo "========================================"

# =====================================================
# Generate pgbouncer.ini from template
# =====================================================
echo "Generating pgbouncer.ini configuration..."

# Export all variables for envsubst
export DB_HOST DB_PORT DB_NAME DB_USER DB_PASSWORD DB_SSL_MODE
export DB_REPLICA_HOST DB_REPLICA_PORT
export PGBOUNCER_POOL_MODE PGBOUNCER_MAX_CLIENT_CONN PGBOUNCER_DEFAULT_POOL_SIZE
export PGBOUNCER_MIN_POOL_SIZE PGBOUNCER_RESERVE_POOL_SIZE PGBOUNCER_MAX_DB_CONNECTIONS

# Substitute environment variables in the template
envsubst < /etc/pgbouncer/pgbouncer.ini.template > /etc/pgbouncer/pgbouncer.ini

# =====================================================
# Generate userlist.txt for authentication
# =====================================================
echo "Generating user authentication file..."

# Function to generate MD5 password hash for PgBouncer
# Format: "md5" + md5(password + username)
generate_md5_hash() {
    local user="$1"
    local pass="$2"
    echo -n "md5$(echo -n "${pass}${user}" | md5sum | cut -d' ' -f1)"
}

# Generate hashed passwords
DB_USER_HASH=$(generate_md5_hash "${DB_USER}" "${DB_PASSWORD}")
ADMIN_HASH=$(generate_md5_hash "${PGBOUNCER_ADMIN_USER}" "${PGBOUNCER_ADMIN_PASSWORD}")
STATS_HASH=$(generate_md5_hash "${PGBOUNCER_STATS_USER}" "${PGBOUNCER_STATS_PASSWORD}")

# Create userlist.txt with MD5 hashed passwords
# Format: "username" "password_hash"
cat > /etc/pgbouncer/userlist.txt << EOF
# =====================================================
# PgBouncer User Authentication File
# Generated by entrypoint.sh
# Passwords are MD5 hashed for security
# =====================================================

# Database user
"${DB_USER}" "${DB_USER_HASH}"

# Admin user for PgBouncer console
"${PGBOUNCER_ADMIN_USER}" "${ADMIN_HASH}"

# Stats user for monitoring
"${PGBOUNCER_STATS_USER}" "${STATS_HASH}"
EOF

# Set secure permissions
chmod 600 /etc/pgbouncer/userlist.txt

# =====================================================
# Update pgbouncer.ini with dynamic pool settings
# =====================================================
# Override template values with environment-specific settings
sed -i "s/pool_mode = .*/pool_mode = ${PGBOUNCER_POOL_MODE}/" /etc/pgbouncer/pgbouncer.ini
sed -i "s/max_client_conn = .*/max_client_conn = ${PGBOUNCER_MAX_CLIENT_CONN}/" /etc/pgbouncer/pgbouncer.ini
sed -i "s/default_pool_size = .*/default_pool_size = ${PGBOUNCER_DEFAULT_POOL_SIZE}/" /etc/pgbouncer/pgbouncer.ini
sed -i "s/min_pool_size = .*/min_pool_size = ${PGBOUNCER_MIN_POOL_SIZE}/" /etc/pgbouncer/pgbouncer.ini
sed -i "s/reserve_pool_size = .*/reserve_pool_size = ${PGBOUNCER_RESERVE_POOL_SIZE}/" /etc/pgbouncer/pgbouncer.ini
sed -i "s/max_db_connections = .*/max_db_connections = ${PGBOUNCER_MAX_DB_CONNECTIONS}/" /etc/pgbouncer/pgbouncer.ini

# =====================================================
# Validate configuration
# =====================================================
echo "Validating PgBouncer configuration..."

if [ ! -f /etc/pgbouncer/pgbouncer.ini ]; then
    echo "ERROR: pgbouncer.ini not found!"
    exit 1
fi

if [ ! -f /etc/pgbouncer/userlist.txt ]; then
    echo "ERROR: userlist.txt not found!"
    exit 1
fi

echo "Configuration files validated successfully."

# =====================================================
# Start PgBouncer
# =====================================================
echo "Starting PgBouncer..."
echo "========================================"

# Execute the command passed to the container
exec "$@"
